framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: order_manager_app

        # Redis cache adapter
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Define cache pools
        pools:
            cache.application:
                adapter: cache.adapter.redis
                default_lifetime: 3600

            cache.settings:
                adapter: cache.adapter.redis
                default_lifetime: 86400

when@dev:
    framework:
        cache:
            # Use filesystem cache in dev for easier debugging
            app: cache.adapter.filesystem

when@test:
    framework:
        cache:
            app: cache.adapter.array
            pools:
                cache.application:
                    adapter: cache.adapter.array
                cache.settings:
                    adapter: cache.adapter.array
